### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/WEASEL#23]
C:\Users\medkshaa\Documents\WEASEL-master\WEASEL-master>python setup.py clean
running clean
Weasel.egg-info, Are you sure (Y/N)? Y

C:\Users\medkshaa\Documents\WEASEL-master\WEASEL-master>python Weasel.py
Traceback (most recent call last):
  File "Weasel.py", line 27, in <module>
    import CoreModules.WEASEL.Menus  as menus
  File "C:\Users\medkshaa\Documents\WEASEL-master\WEASEL-master\CoreModules\WEASEL\Menus.py", line 9, in <module>
    import CoreModules.WEASEL.TreeView  as treeView
  File "C:\Users\medkshaa\Documents\WEASEL-master\WEASEL-master\CoreModules\WEASEL\TreeView.py", line 11, in <module>
    import CoreModules.WEASEL.Menus  as menus
AttributeError: module 'CoreModules.WEASEL' has no attribute 'Menus'

**Comment by JSousa-UoL** [comment]
Hi @KanishkaS , I managed to replicate this issue by going to my personal laptop and install a clean version of Python 3.6.6. It didn't happen when I did the exact same using Python version 3.7. I will keep investigating this to solve the issue in my personal laptop, but if you want to try and test Weasel sooner, you may give it a try by using 3.7 or higher in your Windows machine. I'll inform you if I solve this for 3.6

**Comment by JSousa-UoL** [comment]
@KanishkaS , the Python Windows 3.6.6 issue should have been solved now. Please try again when possible and let me know the outcome and if Weasel starts correctly on your side.

**Comment by KanishkaS** [comment]
Thanks, Joao! It works now.

**Comment by JSousa-UoL** [comment]
I'm reopening this issue as this solution is not the best in the long-term. I found out that Python 3.6 has a critical bug in circular import (which doesn't happen in 3.5, 3.7, 3.8 and 3.9). This affects this project because it's not possible to generate the executable (.exe) without circular.

@KanishkaS would it be possible for you to upgrade your Python to 3.7. or higher in your Windows machine without uninstalling the current packages you have?

@IMI-TRISTAN I think in the README.md file we'll have to state that the minimum requirement is Python >= 3.7

**Comment by JSousa-UoL** [comment]
Will close this issue as it's solved for now. If new installation queries come up, then new issues will be written
