### ISSUE TITLE
Folder structure - consider external developers

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#36]
An external developer will not save their pipelines and external packages inside the weasel distribution - they would have to disentangle them every time weasel is updated. Rather it will be the other way around. Weasel is downloaded inside their packages and not otherwise changed. So we need a folder structure like this to work I think:

MySoftwarePackage
> WEASEL
> MyWeaselPipelines
> MyWeaselConfigurations
> MyOtherCode

Can Weasel search for pipelines and configurations in its top folder (MySoftwarePackage) and all subfolders?
Where should the config file go? First search in sibling folders of WEASEL and then call config inside Weasel when none found?

**Comment by JSousa-UoL** [comment]
I will add the parent folder to Weasel.py. This is because this will partly affect the work I'm doing in issue #36

**Comment by JSousa-UoL** [comment]
This is done now. Please test to confirm it's doing as expected. My test was putting "Tutorials" folder and "PipelineBuildingTutorial.xml" in my Desktop and it worked:

WEASEL
Tutorials (equivalent of "MyWeaselPipelines")
PipelineBuildingTutorial.xml (equivalent of "MyWeaselConfigurations")

It took me a while to do this because adding the parent folder to the system was making the start-up of Weasel very slow, but that was corrected in the meantime.

**Comment by plaresmedima** [comment]
This seems to be working fine. I moved the iBEAt pipelines and configurations to a separate folder and it's all running fine. I will continue working like this setup and make a separate Github repository for "my" pipelines. Will add you to that. 

Closing this issues
