### ISSUE TITLE
Series.write() bug

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#48]
@JSousa-UoL This is a dangerous bug:

Series.write(Series.PixelArray)

This replaces all images of the series by the first one. 

It came up in Template_InvertPixelValuesSeries.py

**Comment by KanishkaS** [comment]
@JSousa-UoL: I believe the error I have is related to this issue. On pressing invert series on the iBEAt menu. It overwrites the images on the same tree view (or does not save them). I can see the inverted images + original on the display but I cannot distinguish original from invert from the tree view.

**Comment by KanishkaS** [comment]
Ok -It just overwrote my original dicom files in the original folder instead of just inverting them on Weasel.

**Comment by JSousa-UoL** [comment]
I see there's some confusion about the .write() function in the Series class of the DeveloperTools.

In the case of the Invert, because you're not creating a new series, the .write() will overwrite any images existing in the series. If you create a variable "new_Series" by using the .new() method, then new_Series.write(PixelArray) will save the PixelArray into new DICOM files. This was what was agreed at the time for the Developer's module but we can revisit this now. 

I think the best way is to discuss this in a call as it seems to me it's not clear what this .write() is meant to do. We can schedule a call to discuss this in more detail.

As for the windows/viewers, if you run Invert, you will observe the overwritten series in a new viewer. The "old" window will still display the image as it was before because it doesn't update automatically I think. But I wouldn't worry about the visualisation for now, the bigger issue is overwriting the image.

Also, have a look at Square and Gaussian algorithms as they contains mechanisms to save PixelArray into a new series. When I wrote the Invert, it was on purpose to overwrite at the time.

**Comment by plaresmedima** [comment]
Hi Joao,

yes that was actually clear. I think if you try it you will see what I
mean.

Check a series with several different images, then
run Template_InvertPixelValuesSeries.py.

In the resulting series, all the images are now the same.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
I had a good look and I understood the problem. I made a new commit and it should be solved now. The issue was in the overwriting function I wrote that had a few incorrections. Please test and have a look.
