### ISSUE TITLE
current version of checkT2(seriesMagnitude)/checkT2Star(seriesMagnitude) does not work - issue with series check

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/WEASEL#53]
check series criteria required for mapping functions does not work for iBEAt.

**Comment by KanishkaS** [comment]
@JSousa-UoL: Have you tested this before on iBEAt dataset?

**Comment by JSousa-UoL** [comment]
You can show me this in the meeting. There is the file "T1Map_iBEAT.py" under the UKRIN-MAPS folder and that should work, although it will not work at the moment because I was asked to remove a file so that became obsolete. I'll be sending you an email with a file where I wrote a T1Map function as translation of your Matlab code.
