### ISSUE TITLE
Bug when running Tutorial_InvertPixelValuesSeriesInNewSeries

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#59]
**Tutorial_InvertPixelValuesSeriesInNewSeries** was working before except from the Display() issue in the loop.

Now a new problem comes up. I select two series to invert and run **Tutorial_InvertPixelValuesSeriesInNewSeries**. Then two "None" series are created.

![image](https://user-images.githubusercontent.com/6051075/108570261-57342d00-7305-11eb-8ede-4e2eb98cdd9e.png)

This then throws up these errors

Error in InterfaceDICOMXMLFile.getNewSeriesName: 'NoneType' object has no attribute 'SeriesNumber'
Error in WeaselXMLReader.insertNewSeriesInXML: cannot serialize None (type NoneType)
Error in InterfaceDICOMXMLFile.insertNewSeriesInXMLFile: can only concatenate str (not "NoneType") to str
WeaselXMLReader.parseConfigFile error: unclosed token: line 66429, column 1404000

**Comment by JSousa-UoL** [comment]
Tagging issue #58 where the solution at the time was to remove the getParentNode() in displayImages(). The real problem is that the Display and saving to XML are tightly connected and my biggest concern is that the XML re-writing might need profound re-writing. Let's hope that won't be the case but I'll continue to investigate this. Issue #56 is also a bit connected to this.

**Comment by plaresmedima** [comment]
Would it be a solution to also record in the XML which items are checked or not? Then you can create a clear dividing line between GUI functioanlity and file management. Basically when a series of computations is performed, new series/images created or deleted etc, then this all goes via the XML only, and the treeview is updated at then end with Weasel.Refresh(). It will make the refresh function a lot cleaner as well - you basically always expand in the treeview whathever is checked.

**Comment by JSousa-UoL** [comment]
I have my reservations about recording the checked items in XML - that's more of a question for Steve. But I do agree regarding the cleaner approach of expanding the TreeView. I've been spending time on that and it's going to take a while as I need to read a lot of CoreModules code and understand that fully and find a suitable solution.

**Comment by JSousa-UoL** [comment]
I'm not managing to replicate this problem. When I select 3 series and run that script I'm able to see all 3 resulting series. I highly recommend that you delete the XML file and even get a clean version of the software if possible. When a bug is related with writing XML, this file can get corrupted and if it's not re-generated then other problems may occur due to the file being corrupted. @plaresmedima could you try to delete that dataset's XML and Load the DICOM files again and run this script please? Does the same error occur?

**Comment by plaresmedima** [comment]
I deleted the XML file and reloaded but the problem still exists.

It seems to happen only when I select the last series in the list, not when I select one in the middle

**Comment by JSousa-UoL** [comment]
Managed to reproduce this issue - really good spot and interesting to have a look at. It's not related with the Display() solution, I reverted it temporarily and got the same error. The error is in the interfaceXML.py and need to consider the last series of a study in future tests.
