### ISSUE TITLE
saveDICOM - dealing with corrupted files

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#77]
getImageList: studyID=20190115_091054, seriesID=10339246_*fl2d1_v120in_Invert_Copy
Error in function saveDICOM_Image.saveDicomToFile: [Errno 22] Invalid argument: 'C:\\Users\\steve\\Dropbox\\Data\\BEAt-DKD\\ssourbron-20201109_153111\\ssourbron-20201109_153111\\Leeds_Patient_4128005\\10\\DICOM\\output_Invert\\output_Copy\\output_Copy\\1.3.12.2.1107.5.2.43.66097.30000019011510461753600000001-10-10-nhd38k_Invert_Copy_Copy.dcm'
getImageList: studyID=20190115_091054, seriesID=10339246412_*fl2d1_v120in_Invert_Copy_Copy

And upon running CopySeries

Error in saveDICOM_Image.overwriteDicomFileTag: 'NoneType' object has no attribute 'add_new'
Error in saveDICOM_Image.overwriteDicomFileTag: 'NoneType' object has no attribute 'add_new'
Error in saveDICOM_Image.overwriteDicomFileTag: 'NoneType' object has no attribute 'add_new'
Error in saveDICOM_Image.overwriteDicomFileTag: 'NoneType' object has no attribute 'add_new'
Error in InterfaceDICOMXMLFile.getNewSeriesName: local variable 'seriesID' referenced before assignment
Error in WeaselXMLReader.insertNewSeriesInXML: cannot serialize None (type NoneType)
Error in InterfaceDICOMXMLFile.insertNewSeriesInXMLFile: can only concatenate str (not "NoneType") to str
WeaselXMLReader.parseConfigFile error: unclosed token: line 71215, column 95579

**Comment by JSousa-UoL** [comment]
That seems extremely odd, I never had such error. I also need more details about the context. 
I will synchronise tomorrow and try to have a look.
Did this happen while running the CopySeries?

**Comment by plaresmedima** [comment]
Yes during CopySeries. It's reproducible but it does not happen all the time and when I reload the DICOM data folder everything os fine again.

It seems to happen if I apply CopySeries to the laste series in the study, or the one before that.

**Comment by JSousa-UoL** [comment]
The 2nd paragraph/block is mainly because the XML file is corrupted. You have to load the DICOM files again. The important thing is to understand how the first error happened.

**Comment by plaresmedima** [comment]
See my comment above..

**Comment by JSousa-UoL** [comment]
I cannot replicate this bug, but I think I know what's the root and fundamental cause. 
In early days I had this error quite often, because what happens is that when the DICOM save goes wrong, the XML writing goes wrong as a consequence. There are lots of controls and error managements but I can see what more controls I can add to the write function. XML writing only happens when DICOM is saved but pydicom sometimes is "funny" and creates DICOM file but with no actual content and then proceeds to XML writing "thinking" everything is alright. Will investigate more controls to add.

This is an error that I expect to happen less and less with time. Unfortunately, it's not a type of error that we'll get 100% rid of, because it's very dependent of multiple factors, especially from pydicom. When this sort of error happens during development, I recommend that you delete all output folders within the dataset you're analysing @plaresmedima. The perception that I have at the moment is that this type of error is rare.

**Comment by JSousa-UoL** [comment]
Suggestion for myself: try to read the newly saved and/or created DICOM file before moving on. If it reads correctly, then it's all good. If not, it deletes the file and log that in the Activity Log. No need to read whole file, just the essential tags.

**Comment by plaresmedima** [comment]
OK I will download a whole new DICOM dataset and see if it happens again. I
have been testing with the same DICOM dataset for a while and perhaps it
got corrupted along the way. Still we need some good way of handling
corrupted files - if that is the problem.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
That's it and that's the right wording, dealing with corrupted files.
