### ISSUE TITLE
weasel.series() very slow

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#86]
list_of_series = weasel.series() 

This line takes a few minutes for a single iBEAT dataset.

**Comment by JSousa-UoL** [comment]
This is an important topic.

After investigating this, the reason for this slow command is the fact that ".children" is a class attribute. If it's a function of the class, then this command runs in 1 or 2 seconds. The current code gets a list of Images for every checked series and that takes a long time. The correct thing to do is to have a function children(self) instead of it being an attribute.

This will involve a couple/few hours of changing the DeveloperTools.py. The impact is that in tutorials you'll have to write "ds = series.children()[0].read()" instead of the current "ds = series.children[0].read()" (difference is in the brackets). Same with numberOfChildren.

**Comment by JSousa-UoL** [comment]
However, it's also worth noting that some recent commit has provoked this huge delay. On Friday, everything was looking fine to me, but today I ran invert Series on 1 checked series and it almost took a minute to start the progress bar,

**Comment by plaresmedima** [comment]
Can it be like this?

ds = series.children(0).read()

**Comment by plaresmedima** [comment]
Yes let's convert multi-frame to single-frame when the folder is first
opened, but let's do it in a copy of the folder so original data are not
deleted by default.

It would be good to allow for multi-frame but let's keep that for a future
version. Can you stash your multi-frame code somewhere separate so it does
not get lost?

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
Ok, thanks for the feedback. Will commit my work later.

I will just comment out the multi-frame part. If stash it somewhere, it'll be easy to lose it and forget what was done.
