### ISSUE TITLE
Identify sequences by SeriesInstanceUID

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#94]
Sequences with the same Series Instance UID show up as different sequences in TreeView.

(If this is part of another issue please close this)

**Comment by JSousa-UoL** [comment]
There was a similar one but it was closed already.

I spent considerable amount of time having a look at this last week. Couldn't come up with a reasonable solution, because any of the most obvious solutions would break the DICOM-TreeView-XML flow and probably could only show the UIDs values in the TreeView, which are not readable for the normal user. We can think about this again after the first milestone and spend more time in trying to figure something out.

For the case of iBEAt, the temporary solution would be to use the merge script.

**Comment by plaresmedima** [comment]
Let's look at it together. If we don't fix it now this will trigger a lot of unnecessary scripting that will later have to be reversed. This is definitely a v0.1 issue.

**Comment by JSousa-UoL** [comment]
Seems I had a comment written 3 days ago but didn't submit...

This should be done in the commit mentioned above. At the moment what's happening is that if there is no "SeriesDescription" DICOM tag, the loading script will add that tag with "No Series Description". The UID is also in the data's XML file.

However, I would avoid closing this issue in the next couple of weeks. I'd like to confirm that everyone is happy with this approach. Once everyone's happy then I can finish the final tasks I still have for this issue => which are to remove the lines of code in the project that contain "SequenceName" and "ProtocolName"
